default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: mzhao
  timeout: 5000

development:
  <<: *default
  database: oldschool_chatroom_development

test:
  <<: *default
  database: oldschool_chatroom_test

production:
  <<: *default
  database: oldschool_chatroom_production
